name: Lint, Test & Deploy on "push"
on: push
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Run run test
        run: npm test
      - name: Run build
        run: npm build
  