name: issues and github context
on: issues
jobs:
  issues-context:
    runs-on: ubuntu-latest
    name: output detail
    steps:
      - name: echo issues
        run: echo "${{ github.action_status}}"